[visuals]
note_color_pressed = 0xffffff
note_color = 0x7f7f7f
note_height = 10.0
note_padding_y = 1.0
text_color = 0xffffff
background_color = 0x00ff00
tickscene_width = 1000                  # Lower means notes are more wider
current_tick_indicator_x_offset = 200
current_tick_indicator_color = 0xff0000

[system]
fps = 90
midi_path = 'C:\Windows\Media\onestop.mid'
synthesizer_volume = 0.1
window_size = { w = 1920, h = 1080 }       # Between 0 and 1
playback_speed = 1
